### ISSUE TITLE
LSC not working with Python3

### ISSUE THREAD

**Issue by huymetocean** [calypso-science/schism#1]
Hi  Remy,
That's great to see you have updated LSC from PyQt4 to Qt5, but h ave you got LSC code worked with Python 3?  

I tested your updated code, I got the following error:

python lsc.py design_NZG2000.gr3.grd
Traceback (most recent call last):
  File "lsc.py", line 776, in <module>
    window = MyApp(app)
  File "lsc.py", line 258, in __init__
    self.draw_map()
  File "lsc.py", line 435, in draw_map
    self.els[I+1,:]=elem[q,[0,2,3]]
IndexError: index 3 is out of bounds for axis 1 with size 3

Thanks Remy

Cheers,
Huy

**Comment by huymetocean** [comment]
Hey Remy. Wonderful.. It's working now... please see a screenshot that I  directly run LSC with Python 3 from  command promt

I changed:           line 435 from  	self.els[I+1,:]=elem[q,[0,2,3]] =             	self.els[I+1,:]=elem[q,[0,1,2]]

Also, I have to updated:
# from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
# from matplotlib.backends.backend_qt4 import NavigationToolbar2QT as NavigationToolbar
from matplotlib.backends.backend_qt5agg import (FigureCanvasQTAgg as FigureCanvas)
from matplotlib.backends.backend_qt5agg import  NavigationToolbar2QT as NavigationToolbar

Can I make a pull request for qt5?
![Screenshot from 2020-08-31 10-53-15](https://user-images.githubusercontent.com/66401175/91673596-379f2180-eb78-11ea-8c54-252f3ff1cdf6.png)
